# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_eNdq8D9taBmb7bDIutwx7zbKvROkO6
"""

import re
import random

# =========================
# Reflexões
# =========================
reflexoes = {
    "eu": "você",
    "meu": "seu",
    "minha": "sua",
    "sou": "é",
    "estou": "está",
    "tenho": "tem",
    "mim": "você"
}

def refletir(frase):
    palavras = frase.lower().split()
    return " ".join([reflexoes.get(p, p) for p in palavras])


# =========================
# Controle de repetição
# =========================
ultima_resposta = ""

def escolher_resposta(lista):
    global ultima_resposta
    resposta = random.choice(lista)

    while resposta == ultima_resposta and len(lista) > 1:
        resposta = random.choice(lista)

    ultima_resposta = resposta
    return resposta


# =========================
# Padrões e respostas
# =========================
padroes_respostas = [

    (r"eu estou (.*)", [
        "Por que você está {}?",
        "Como você se sente estando {}?",
        "O que fez você ficar {}?"
    ]),

    (r"eu me sinto (.*)", [
        "Por que você se sente {}?",
        "Você costuma se sentir {} com frequência?",
        "O que te faz sentir {}?"
    ]),

    (r"eu sou (.*)", [
        "Por que você acha que é {}?",
        "Você gosta de ser {}?",
        "Desde quando você é {}?"
    ]),

    (r"meu pai(.*)", [
        "Fale mais sobre seu pai.",
        "Como é sua relação com seu pai?",
        "Seu pai influencia você?"
    ]),

    (r"minha mãe(.*)", [
        "Fale mais sobre sua mãe.",
        "Você tem uma boa relação com sua mãe?",
        "Sua mãe é importante pra você?"
    ]),

    (r"não sei|nao sei", [
        "Tudo bem não saber. Quer tentar explicar melhor?",
        "Às vezes é difícil mesmo. O que você está pensando agora?",
        "Sem problemas. Podemos explorar isso juntos."
    ]),

    (r"mal|triste|deprimido", [
        "Sinto muito que você esteja se sentindo assim.",
        "Quer me contar o que está te deixando assim?",
        "Isso acontece com frequência?"
    ]),

    (r"oi|olá|ola|eai", [
        "Olá! Como você está?",
        "Oi! Me conte o que está acontecendo.",
        "E aí! Como você se sente hoje?"
    ]),

    (r"bem|feliz|otimo|legal|contente", [
        "Que bom ouvir isso! O que está te deixando assim?",
        "Fico feliz que você esteja bem. Quer compartilhar mais?",
        "Isso é ótimo! O que aconteceu de bom?",
        "Que bom! Você costuma se sentir assim com frequência?"
    ]),

    (r"(.*)", [
        "Interessante... me conte mais.",
        "Por que você diz isso?",
        "Como isso te faz sentir?",
        "Pode explicar melhor?",
        "Isso parece importante para você."
    ])
]


# =========================
# Resposta
# =========================
def responder(frase):
    frase = frase.lower()

    for padrao, respostas in padroes_respostas:
        match = re.search(padrao, frase)

        if match:
            resposta = escolher_resposta(respostas)

            if "{}" in resposta:
                grupo = match.group(1)
                grupo = refletir(grupo)
                return resposta.format(grupo)
            else:
                return resposta


# =========================
# Loop principal
# =========================
print("🤖 ELIZA: Olá! Fale comigo. (digite 'sair' para encerrar)\n")

while True:
    entrada = input("Você: ")

    if entrada.lower() == "sair":
        print("🤖 ELIZA: Até mais! Cuide-se.")
        break

    print("🤖 ELIZA:", responder(entrada))