# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_eNdq8D9taBmb7bDIutwx7zbKvROkO6
"""

def gerar_frase_interativa(bigramas, palavra_inicial, tamanho=6):
    palavra = palavra_inicial.lower()
    frase = [palavra]

    for _ in range(tamanho - 1):
        if palavra in bigramas:
            palavra = random.choice(bigramas[palavra])
            frase.append(palavra)
        else:
            break

    return " ".join(frase)


# =========================
# Loop com usuário
# =========================
print("Digite uma palavra inicial (ou 'sair'):\n")

while True:
    entrada = input("Você: ")

    if entrada == "sair":
        break

    if entrada not in bigramas:
        print("Palavra desconhecida, tente outra.")
    else:
        print("IA:", gerar_frase_interativa(bigramas, entrada))
