# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7-JTUa-dEwh39yudvJiTcyN4yNArIFI
"""

from transformers import pipeline

print("==========================================")
print(" GERADOR DE TEXTO COM TRANSFORMERS ")
print("==========================================")

gerador_texto = pipeline(
    "text-generation",
    model="pierreguillou/gpt2-small-portuguese"
)

entrada = input("Digite uma frase para a IA continuar: ")

resultado = gerador_texto(
    entrada,
    max_new_tokens=30,   # 🔥 mais rápido
    temperature=0.7,
    top_k=50,
    top_p=0.95,
    do_sample=True
)

print("\nTexto gerado pela IA:\n")
print(resultado[0]['generated_text'])