# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P7-JTUa-dEwh39yudvJiTcyN4yNArIFI
"""

import sys
!{sys.executable} -m pip install gensim
from gensim.models import Word2Vec

# =========================
# Corpus (texto de treino)
# =========================
sentencas = [
    ["gato", "animal"],
    ["gato", "animal"],
    ["cachorro", "animal"],
    ["cachorro", "animal"],

    ["gato", "cachorro", "pets"],
    ["gato", "cachorro", "pets"],
    ["gato", "cachorro", "animais"],
    ["gato", "cachorro", "amigos"],

    ["gato", "leite"],
    ["gato", "leite"],
    ["gato", "leite"],
    ["gato", "dormir"],

    ["cachorro", "carne"],
    ["cachorro", "carne"],
    ["cachorro", "carne"],
    ["cachorro", "brincar"],

    ["gato", "felino"],
    ["cachorro", "canino"],

    ["pets", "humanos"],
    ["animais", "comer"],
]

# =========================
# Treinar modelo
# =========================
modelo = Word2Vec(
    sentences=sentencas,
    vector_size=50,
    window=2,
    min_count=1,
    workers=1,
    epochs=300,
    sg=1
)

# =========================
# Testes de similaridade
# =========================
print("\n=== Similaridade ===")

print("\nPalavras mais parecidas com 'gato':")
print(modelo.wv.most_similar("gato"))

print("\nPalavras mais parecidas com 'cachorro':")
print(modelo.wv.most_similar("cachorro"))

print("\nSimilaridade entre gato e cachorro:")
print(modelo.wv.similarity("gato", "cachorro"))

print("\nSimilaridade entre gato e leite:")
print(modelo.wv.similarity("gato", "leite"))


# =========================
# Operações vetoriais
# =========================
print("\n=== Operações Vetoriais ===")

print("\nOperação: gato - leite + carne")
try:
    resultado1 = modelo.wv.most_similar(
        positive=["gato", "carne"],
        negative=["leite"]
    )
    print(resultado1)
except:
    print("Erro na operação")

print("\nOperação: cachorro - carne + leite")
try:
    resultado2 = modelo.wv.most_similar(
        positive=["cachorro", "leite"],
        negative=["carne"]
    )
    print(resultado2)
except:
    print("Erro na operação")

print("\nOperação: gato + cachorro")
try:
    resultado3 = modelo.wv.most_similar(
        positive=["gato", "cachorro"]
    )
    print(resultado3)
except:
    print("Erro na operação")